// EXTERNAL
export const REQUEST_JWT_TOKEN   = 'REQUEST_JWT_TOKEN'

// INTERNAL
export const FETCH_PROFILE       = 'FETCH_PROFILE'
export const FETCH_PROFILE_BEGIN = 'FETCH_PROFILE_BEGIN'
export const FETCH_PROFILE_END   = 'FETCH_PROFILE_END'
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR'
