export const REGISTER    = 'AUTH:REGISTER'
export const LOGIN       = 'AUTH:LOGIN'
export const SET         = 'AUTH:SET'
export const ERROR       = 'AUTH:ERROR'
export const LOGOUT      = 'AUTH:LOGOUT'
export const SENDING     = 'AUTH:START'
export const FORM_CHANGE = 'AUTH:FORM_CHANGE'
