export const SENDING_REQUEST = 'SENDING_REQUEST'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const SET_AUTH = 'SET_AUTH'
export const LOGOUT = 'LOGOUT'
export const CHANGE_FORM = 'CHANGE_FORM'
export const REQUEST_ERROR = 'REQUEST_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const CALLING_API = 'CALL_API'
export const RECEIVE_API = 'RECEIVE_API'
export const API_ERROR = 'API_ERROR'
